### ISSUE TITLE
lwjgl.dll过敏.

### ISSUE THREAD

**Issue by RhythmNz** [Southern-InfinityStudio/JMCCC#2]
Jmccc似乎只支持Java8.
而且在32位Java环境下 似乎对
lwjgl.dll过敏.
.minecraft\natives\lwjgl.dll: %1 不是有效的 Win32 应用程序。
这样的提示 而其他启动器均能正确启动
就这些啦 希望给一个答复 大触

**Comment by Darkyoooooo** [comment]
见Mcbbs

**Comment by RhythmNz** [comment]
http://pan.baidu.com/s/1kTF0npd
Logs.

**Comment by Darkyoooooo** [comment]
你确定lwjgl的jar是下载的正确的jar？

**Comment by RhythmNz** [comment]
非常确定.已经使用其他各种启动器启动了

**Comment by Darkyoooooo** [comment]
尝试将游戏客户端放在纯英文路径上 估计是中文路径支持有问题

**Comment by RhythmNz** [comment]
64位可以启动

**Comment by Darkyoooooo** [comment]
http://pan.baidu.com/s/1i3KoaVV 你试试这个能不能启动

**Comment by RhythmNz** [comment]
晚点试试 因为程序是我技术写的 我并不会Java.

**Comment by Darkyoooooo** [comment]
人呢

**Comment by RhythmNz** [comment]
我们家技术一直没粗线

**Comment by RhythmNz** [comment]
我把老版本的上传丢给你研究一下
http://pan.baidu.com/s/1sjQd9iX

**Comment by Darkyoooooo** [comment]
已经解决 确认是BufferedOutputStream的问题
